### ISSUE TITLE
Can't Dig In It?

### ISSUE THREAD

**Issue by scott-martinez** [DavidGriffith/inform6lib#10]
Is using the latest compile from git, try this:

Object lengthofrope "rope" bottomofpit
with name 'rope',
description "It is the rope you climbed down on, now shorter after having been chopped in two.";

>dig in rope
You can't see any such thing.

>dig rope
Digging would achieve nothing here.

Shouldn't these both work?

**Comment by scott-martinez** [comment]
FYI: My only reason for trying odd commands like this is just to look for bugs. I try different commands from http://pr-if.org/doc/play-if-card/ in various ways and look for things.

**Comment by DavidGriffith** [comment]
Oh, I very much appreciate you trying odd commands to see if the library breaks.  I would have been rather embarrassed to see that "hears" bug in an official release.

**Comment by DavidGriffith** [comment]
It looks like this has been the default response all along.  I fixed it and some similar problems with JUMP.  See https://github.com/DavidGriffith/inform6lib/commit/63c6ae69c917ae9d9203d49ff6d79894ab415c15
