### ISSUE TITLE
A spurious "You can't go that way."

### ISSUE THREAD

**Issue by scott-martinez** [DavidGriffith/inform6lib#18]
It is not clear to me why this sample code would result in a "You can't go that way" after the player has already been moved to that location. Compiled with the latest from git, the output is as follows. (Even though they try to go south, the game moves them east.)

I have another example of this where the number "1" is printed after moving. I'll try to reduce that down to the minimum necessary to reproduce it and send that later.

Room 1
This is a very boring place.

>s

Room 3
This is yet another very boring place.
You can't go that way.

Constant Story "Test";
Constant Headline
"^An example.^";
Include "Parser";
Include "VerbLib";

Object  Room1 "Room 1"
  with  description
            "This is a very boring place.",
        s_to Room2,
        e_to Room3,

	Before [;
	Go:
	PlayerTo(Room3);
	],

   has  light;

Object  Room2 "Room 2"
  with  description
            "This is another very boring place.",
        n_to Room1,
   has  light;

Object  Room3 "Room 3"
  with  description
            "This is yet another very boring place.",
        w_to Room1,
   has  light;

[ Initialise; 
Location = Room1; ];

Include "Grammar";

**Comment by scott-martinez** [comment]
Here's some sample code where, if you go through the window, you end up in your neighbor's back yard but a spurious "1" is printed after the description of the back yard.

Constant NO_SCORE;
Constant Story "Test";
Constant Headline
"^A sample.^";
Include "Parser";
Include "VerbLib";

Object kitchen "Kitchen"
	with description "You are in a kitchen. There is a window here which you should try to go through.",
	has light;

Object window "window" kitchen
        with name 'window',
        description "Framed by celery green curtains, you see nothing special about the window.",
	Before [;
	Climb,Enter:
	print_ret "You squeeze yourself into the window and fall out the other side.^",
	PlayerTo(backyard);
	],
        has scenery container openable;

Object backyard "Back Yard"
  with  description
            "You are in your neighbor's back yard. It is barely cloudy and already hot this morning. The healthy, dark green grass is well manicured. A high wooden fence encompasses the area, painted a burnt umber. The back door is to the east. Your kitchen window is to the south.",
          before [; Go:
              if (noun == s_obj) {
                  print "Climbing over the fence you squeeze back through your kitchen window.^";
                  }
              ],
        s_to kitchen,
   has  light;

[ Initialise;

Location = Kitchen; 

];

Include "Grammar";

**Comment by DavidGriffith** [comment]
Moved second bug to its own issue report.

**Comment by DavidGriffith** [comment]
The "You can't go that way" happened because the Before rule of Room1 reached its end.  The default return value from a rule is false.  See page 80 of DM4.  If a rule returns false, that tells the parser that whatever was attempted failed and therefore that it should print something appropriate.  In this case, the default failure to "Go" is "You can't go that way.".  Returning true indicates that whatever was done succeeded and so the parser should not comment any further.  So, you should have put "rtrue" after the PlayerTo() call.
