### ISSUE TITLE
Maintain change log document under a single name

### ISSUE THREAD

**Issue by bignose-debian** [DavidGriffith/inform6lib#27]
Please maintain a change log document under a single name that stays the same for each version, e.g. ‘CHANGES’. This allows the same document to accumulate user-visible changes (conventionally, starting with the latest version and proceeding to older versions) as a common reference document.

If you like, you could incorporate the previous changes for version 6.11 into the ‘CHANGES’ document, though that isn't necessary for resolving this issue.

**Comment by DavidGriffith** [comment]
Also fixed by https://github.com/DavidGriffith/inform6lib/commit/c718d6c858b545f17541142630078ded30d65de1
