### ISSUE TITLE
Put release date of each version in change log document

### ISSUE THREAD

**Issue by bignose-debian** [DavidGriffith/inform6lib#28]
In the change log document, please state the date of release of each version.

For example:

    Version 6.12
    ============

    Released: 2015-12-20

    New features
    ------------

    […]

    Version 6.11
    ============

    Released: 2011-12-21

    New features
    ------------

    […]

or:

    Version 6.12 (released 2015-12-20)
    ==================================

    New features
    ------------

    […]

    Version 6.11 (released 2011-12-21)
    ==================================

    New features
    ------------

    […]

**Comment by DavidGriffith** [comment]
Note: the changelogs to previous versions are lost to the mists of time.
