### ISSUE TITLE
Source and tool to generate ‘infglk.h’

### ISSUE THREAD

**Issue by bignose-debian** [DavidGriffith/inform6lib#35]
The file `infglk.h` is auto-generated. The source for this file is not apparent in the `inform6lib` source.

What is the preferred form of `infglk.h` for making modifications? In other words, from what source file is it generated?

Where is the specified `glk2inf.pl` tool for generating this file from its source?

**Comment by DavidGriffith** [comment]
The file ``infglk.h`` is from https://github.com/erkyrath/glk-dev and generated by ``parse_dispatch.py``.  I'm not sure where you're seeing ``glk2inf.pl``.

**Comment by bignose-debian** [comment]
I see that a later version of the file describes it is “auto-generated by parse_dispatch.py”.

So it is the source form used as input, and the `parse_dispatch.py` program, that is needed in order for recipients to effectively have freedom to modify this work.

**Comment by bignose-debian** [comment]
Okay, thanks @DavidGriffith.

So it looks like the `glk-dev` tools are a build dependency for `inform6lib`. I will look into that.

**Comment by bignose-debian** [comment]
The `glk-dev` tools themselves require a Glk API library in order to build. There seems only to be a non-free implementation ([cheapglk](https://github.com/erkyrath/cheapglk/)).

Is there a different way to generate `infglk.h`, using only free-software source and build tools?

**Comment by DavidGriffith** [comment]
I just now emailed Andrew Plotkin about this.

**Comment by bignose-debian** [comment]
Thanks. Andrew P. has deliberately chosen terms that expressly freedom to modify on ‘cheapglk’, so I will proceed on the assumption that `infglk.h` cannot be generated with free-software tools.

If there is a better solution – such as ‘cheapglk’ released with a grant of free-software license terms like the Apache License 2.0 – that would be ideal. I won't pester Andrew for that though.

For now, I will omit the non-source `infglk.h` file.

**Comment by DavidGriffith** [comment]
I asked Andrew for the license change.  Since we've been working together on stuff like this for a long time, I figure he won't get too offended if he doesn't want to do so.

**Comment by curiousdannii** [comment]
https://github.com/erkyrath/cheapglk/blob/master/notes.txt

> The source code in this package is copyright 1998-2012 by Andrew Plotkin. You
may copy and distribute it freely, by any means and under any conditions,
as long as the code and documentation is not changed. You may also
incorporate this code into your own program and distribute that, or modify
this code and use and distribute the modified version, as long as you retain
a notice in your program or documentation which mentions my name and the
URL shown above.

It's a crayon license, but it seems free to me.

**Comment by bignose-debian** [comment]
@curiousdannii:

> It's a crayon license, but it seems free to me.

I like the term “crayon license” :-)

Yes, after parsing it again I see that it grants all the freedoms needed, conditional only on retaining an attribution notice. This is fine for free software.

Thanks to everyone for taking this seriously, this is no longer a problem.
