### ISSUE TITLE
Opening Door Reveals Nothing?

### ISSUE THREAD

**Issue by scott-martinez** [DavidGriffith/inform6lib#8]
>open door
You open the steel door, revealing nothing.

Why does opening the door reveal nothing? I'm not sure what it should say instead, but "revealing nothing" seems strange to say since there is a room beyond it. A small sample:

Constant Story "A small sample^";
Include "Parser";
Include "VerbLib";

Object hallway "Hallway"
        with description
	"An unremarkable hallway with a strong steel door at the end.",
	e_to steel_door,
	has light;

Object steel_door "steel door" hallway
	with name 'door' 'steel' 'steel door',
	description "Gunmetal grey in color it appears to be a very solid and hefty door.",
	door_dir e_to,
	door_to anteroom,
	has scenery door openable;

Object anteroom "Quarantine Anteroom"
	with description
	"The floor is covered in square tiles, alternating white and 
	black. There's nothing here. What do you expect in a simple demo?",
	has light;

[ Initialise; location = hallway;
]

Include "Grammar";

**Comment by DavidGriffith** [comment]
Fixed: 02cae56bacc20b3892641e87e93e5ea58f512aca
