### ISSUE TITLE
Hears?

### ISSUE THREAD

**Issue by scott-martinez** [DavidGriffith/inform6lib#9]
Is using the latest compile from git, try this:

Object lengthofrope "rope" bottomofpit
        with name 'rope',
        description "It is the rope you climbed down on, now shorter after having been chopped in two.";

>listen to rope
you hears nothing unexpected.

I think this should be "hear."

**Comment by DavidGriffith** [comment]
Correct.  And "you" should be capitalized.

**Comment by DavidGriffith** [comment]
Fixed: https://github.com/DavidGriffith/inform6lib/commit/41c090d7d458fde671b5793482840c02cf46ff7c
